name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    env:
      Solution_Name: TerraFirmaGregCalculator.sln
      Output_Dir_Name: ./Release
      Test_Project_Path: ./Tests/TerraFirmaGregCalculator.Test/TerraFirmaGregCalculator.Test.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Run unittests
      run: dotnet test ${{ env.Test_Project_Path }}

#    - name: Publish
#      run: dotnet publish ${{ env.Solution_Name }} -c Release -o ${{ env.Output_Dir_Name }}

